
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/survey
    username:
    password:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      cache:
        use_second_level_cache: true
        region:
          factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        use_query_cache: true

    show-sql: true
logging:
  level:
    com:
      example:
        studentserviceapplication: DEBUG
    root: info
application:
  web:
    self:
      address: https://self.shahroodut.ac.ir/identity/login
      username: 9718223
      password: Az@r1234
server:
  port: 8081
