
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/survey
    username:
    password:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

    show-sql: true

server:
  port: 8081